### ISSUE TITLE
Googlebot regex collision

### ISSUE THREAD

**Issue by drawmyattention** [JayBizzle/Crawler-Detect#135]
When I add the following user agent to the ```devices.txt``` test file:

**Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)**

The tests fail. However, when I add ```Googlebot``` to the ```Crawlers.php``` file, PHPUnit fails because there is a regex collision.

**Comment by JayBizzle** [comment]
Hi,

Bot user agents should be added to `crawlers.txt` not `devices.txt`

When you add `Googlebot` to the `Crawlers.php` array, the tests will fail because `Googlebot` is already detected by our generic regex which you can [see here](https://github.com/JayBizzle/Crawler-Detect/blob/master/src/Fixtures/Crawlers.php#L709)

Thanks
