### ISSUE TITLE
Add crawler detecting via ip adress

### ISSUE THREAD

**Issue by xilnick** [JayBizzle/Crawler-Detect#149]
Hello,
I think it would be great to add detection of the crawlers using a client ip address.
May be some resources like iplists.com or myip.ms/browse/web_bots/ can be used for obtainig a nearly complete list of the ip addresses.

**Comment by JayBizzle** [comment]
Hi,

Thanks for the suggestion. Detecting via IP address is something we have considered in the past, but ultimately decided against it as we feel it would be difficult to maintain, IP addresses change etc etc.

We are open to being persuaded otherwise, but we can't see it happening in the near future.

Would like to hear other peoples thoughts on this, so will leave this issue open for a while.

Thanks 👍

**Comment by JayBizzle** [comment]
Closing this as it is unlikely this is a route we will go down
