### ISSUE TITLE
Composer dev dependency guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by arkuuu** [JayBizzle/Crawler-Detect#247]
I forked this library in order to make a pull request.
When installing dependencies (including dev), Composer tells me:
```
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```

The `guzzle/guzzle` package is required by `satooshi/php-coveralls`.
This package needs to be upgraded to [v2.0](https://github.com/php-coveralls/php-coveralls/blob/2.0/CHANGELOG.md) to get rid of the old dependency.

It's not that bad, but maybe it could be done in the future?

Thank you so much for this great library!

**Comment by JayBizzle** [comment]
Hi,

Thanks for the info.

Im pretty sure I had to lock Coveralls down to `v.1.*` because we need to test on PHP 5.3. The later versions of Coveralls require PHP >=5.5 I think.

See here where i tried in the past https://github.com/JayBizzle/Crawler-Detect/pull/91

If you know of a way to fix this, then send a PR 👍
