### ISSUE TITLE
Googlebot has been detected.

### ISSUE THREAD

**Issue by Radwan-10** [JayBizzle/Crawler-Detect#253]
Hi Guys,

Thanks for the amazing script , it works amazing for us .

But today we can see that Googlebot with IP 66.249.73.157 has been detected and blocked!
When looking the IP up , it seems to be the real one for Googlebot .

Any way to exclude the well known crawlers :) ?
Thanks again

**Comment by gplumb** [comment]
Note. I am not the author of this library, but I did port it to .net core

This library's intended purpose is to detect crawlers/bots. Whether you use that information to block a request or redact it's content is up to you.

I'd argue that adding exclusion lists is a bad idea since it defeats this purpose.

A better approach would be to expose the regex matches (which is what NetCrawlerDetect does). That way you could compare them against your own subset of crawlers (that you deem desirable) and allow them through.

**Comment by Radwan-10** [comment]
Thumbs up 👍

**Comment by mimmi20** [comment]
Where in the code may I find the command to block detected bots?

**Comment by Radwan-10** [comment]
I dont think you can block it from the code , you can log the bots IPs , then block them from your server config (.htaccess , etc..) .
The code is just to detect them..

**Comment by gplumb** [comment]
Radwan is correct. Another approach would be to call "exit" if a bot is detected (if you don't fancy touching htaccess)

**Comment by alister** [comment]
I don't use this library to stop any bad-bots, for that, I use [semalt-blocker](https://github.com/nabble/semalt-blocker). If a user agent is flagged Crawler-Detect, I'll do something like not recording the visit to a user's profile (as it wasn't a real person looking at it) - but these bots aren't necessarily bad - you would probably want Googlebot to index your page, so it was findable.

**Comment by Radwan-10** [comment]
Got you 👍 , i just added a well known crawlers array to exclude the our good guys 👍

**Comment by JayBizzle** [comment]
Thanks for your input everyone.

If you need anything else @Radwan-10 just let us know 👍
