### ISSUE TITLE
Amazon AWS Crawlers

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [JayBizzle/Crawler-Detect#72]
I've added the following to my crawler detection:
substr(gethostbyaddr($_SERVER['REMOTE_ADDR']),-14)==".amazonaws.com"

Amazon AWS crawls with all kinds of random spoofed user agents, so that this was the only way for me to get rid of them for good.

So maybe that's useful for inclusion despite being based on the remote host, and not the user agent.

**Comment by JayBizzle** [comment]
Thanks for reporting.

I have looked a little into this and adding `amazonaws` as a crawler i think will be too risky. There could be a lot if legitimate hits from this domain.

Probably best to just block it manually for now, as you are doing, unless i get more information to tell me otherwise.

Thanks
